services:
  - type: web
    name: prepai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL
        value: gemini-3.1-flash-lite
